version: "2.20.3"

services:
  kafka:
    image: ${KAFKA_IMAGE}
    networks:
      - my_network
    ports:
      - 9092:9094
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      # Listeners
      - KAFKA_CFG_LOG_RETENTION_HOURS=10
      - KAFKA_CFG_MESSAGE_MAX_BYTES=52428800
      - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=52428800
      - KAFKA_CFG_REPLICA_FETCH_RESPONSE_MAX_BYTES=52428800
  kafka-ui:
    image: ${KAFKA_UI}
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - kafka_ui:/etc/kafkaui
    networks:
      - my_network

    
                    

volumes:
  kafka_data:
  kafka_ui:


networks:
  my_network:
